### ISSUE TITLE
Cannot start ConsoleSample

### ISSUE THREAD

**Issue by RTS007** [spotware/OpenApiPy#10]
I tried to run the ConsoleSample program, but unfortunately I can't jump over the error that pops up. I have tried using different versions of python (3.7, 3.8, 3.9), but they all produce the same result. Below is the text that python throws out: 

    Traceback (most recent call last):
    File "/home/sample/test/main.py", line 44, in <module>
    client = Client(EndPoints.PROTOBUF_LIVE_HOST if hostType.lower() == "live" else EndPoints.PROTOBUF_DEMO_HOST, EndPoints.PROTOBUF_PORT, TcpProtocol)
    File "/home/rs/.local/lib/python3.9/site-packages/ctrader_open_api/client.py", line 13, in __init__
    endpoint = clientFromString(self._runningReactor, f"ssl:{host}:port={port}")
    File "/home/rs/.local/lib/python3.9/site-packages/twisted/internet/endpoints.py", line 2116, in clientFromString
    kwargs = _clientParsers[name](*args, **kwargs)
    File "/home/rs/.local/lib/python3.9/site-packages/twisted/internet/endpoints.py", line 2000, in _parseClientSSL
    return _parseClientSSLOptions(kwargs)
    File "/home/rs/.local/lib/python3.9/site-packages/twisted/internet/endpoints.py", line 1965, in _parseClientSSLOptions
    configuration = CertificateOptions(
    NameError: name 'CertificateOptions' is not defined

**Comment by afhacker** [comment]
Did you run the console app on Windows or Linux?

**Comment by RTS007** [comment]
Linux Mint 20.1

**Comment by afhacker** [comment]
It works fine on Windows and Ubuntu, just tested.

CertificateOptions is part of Twisted package, not sure why inside your system it's couldn't be found by Python.

**Comment by RTS007** [comment]
What version of Twisted do you use? Maybe I can update/downgrade mine.

**Comment by afhacker** [comment]
It uses 21.7.0, you can find the detail on pyproject.toml file.

**Comment by afhacker** [comment]
Thanks for finding a solution for this issue,if the package is not obligatory then how it's installed on my windows and Ubuntu machines? İ didn't install the package.

Hopefully this will save time of others who face the same issue with Twisted related packages.

Regarding why i closed the package, because this is not an issue related to our package and we don't have any control over it, and i was not able to replicate is on my system.
