### ISSUE TITLE
duplicate import OpenApiCommonMessages_pb2 twice

### ISSUE THREAD

**Issue by baotang2118** [spotware/OpenApiPy#16]
Hello,

I read you example and found thing weird, why do you import OpenApiCommonMessages_pb2 twice? I scan many time to make sure not my eyes problem 😂

https://github.com/spotware/OpenApiPy/blob/21d144fc51a797140929153cf9f9451ea27ee2de/samples/ConsoleSample/main.py#L5

https://github.com/spotware/OpenApiPy/blob/21d144fc51a797140929153cf9f9451ea27ee2de/samples/ConsoleSample/main.py#L6

**Comment by afhacker** [comment]
Fixed.
