### ISSUE TITLE
Missing some class instances

### ISSUE THREAD

**Issue by KarolBautrel** [spotware/OpenApiPy#22]
Hey, I am struggling with issue, that there is no instances like ProtoOAApplicationAuthReq or any Proto - instances. I think maybe we are missing here stubs and services which are provided by gRPCio ? Look like we need it and we have in messages directory only pb2 files which are raw data from raw protoc instead of grpc protoc which should be called pb2_grpc.

**Comment by afhacker** [comment]
Hi,

I see you opened a thread on the forum too: https://ctrader.com/forum/connect-api-support/39535?page=1#post-1

The Python message files are generated by Protobuf compiler.

You just have to install the package and then import it, try to run the console sample see if it works for you or not.

**Comment by KarolBautrel** [comment]
Yes I already see that this is working, just vscode and flake 8 does not undertand what is this. Okey then, Ill try to work with it in next week, thank you for the answer

**Comment by afhacker** [comment]
You are welcome, then I will close your issue and also please add a reply to your forum thread that it's resolved.
