### ISSUE TITLE
ClientId or clientSecret is incorrect

### ISSUE THREAD

**Issue by DiMiTriFrog** [spotware/OpenApiPy#23]
When i'm trying to run the code, i'm having this output: 
Connected
Message received: 
 errorCode: "CH_CLIENT_AUTH_FAILURE"
description: "clientId or clientSecret is incorrect"

Disconnected:  [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.

I'm using Python3.11 and macOS

As  request.clientId i'm using my account ID and for request.clientSecret  my pass.

What wrong i'm doing?

**Comment by amusleh-spotware-com** [comment]
Hi,

Please read: https://help.ctrader.com/open-api/
